services:
  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - ./mongodb_data:/data/db
      - ./common/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - web_serv

  backend:
    build: ./
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - ./app/uploads:/app/uploads/hotel-rooms
    environment:
      - MONGO_URL=${MONGO_URL}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_HOST=${HTTP_HOST}
      - LOCAL_PATH=${LOCAL_PATH}
    restart: always
    networks:
      - web_serv

volumes:
  mongo-data:

networks:
  web_serv:
    driver: bridge